from __future__ import annotations

from app.models import (
    AccountSnapshot,
    ActiveBasket,
    FeatureBundle,
    MarketSnapshot,
    OpenClawContext,
    PositionSnapshot,
    RiskState,
    V3PlanRequest,
)


def make_v3_request(
    *,
    halted: bool = False,
    spread_points: float = 8.0,
    last_close: float = 2400.20,
    atr_m15: float = 2.50,
    atr_m5: float = 1.20,
    atr_m1: float = 0.50,
    # Scenario knobs
    adx_h1: float = 0.10,
    di_balance: float = 0.05,
    adx_m15: float = 0.18,
    bb_pos_m5: float = -0.92,
    rsi_m5: float = -0.50,
    bb_pos_m1: float = -0.70,
    rsi_m1: float = -0.30,
    ema20_m5: float = 2400.10,
    ema50_m5: float = 2399.80,
    ema50_m15: float = 2399.50,
    swing_high_h1: float = 2410.00,
    swing_low_h1: float = 2390.00,
    breakout_high_m15: float = 2402.00,
    breakout_low_m15: float = 2395.00,
    bb_width_pct: float = 0.40,
    # Momentum M1
    m1_atr_pct: float = 0.0,
    last3_dir: float = 0.0,
    # Active baskets
    active_baskets: list[ActiveBasket] | None = None,
    # Fundamental
    dxy_slope_z: float = 0.0,
    vix_z: float = 0.0,
    request_id: str = "TEST-XAUUSD-V3M1-2026-05-18T09:00:00Z",
) -> V3PlanRequest:
    return V3PlanRequest(
        schema_version="v3-plan-request.v1",
        request_id=request_id,
        mode="paper",
        timestamp_utc="2026-05-18T09:00:00+00:00",
        symbol="XAUUSD",
        timeframe="M1",
        bar_index=1,
        market=MarketSnapshot(
            bid=last_close - 0.05,
            ask=last_close + 0.05,
            last_close=last_close,
            spread_points=spread_points,
            digits=2,
            stops_level_points=50,
            freeze_level_points=10,
            tick_size=0.01,
            tick_value=1.0,
        ),
        account=AccountSnapshot(
            login="demo-1",
            balance=10000.0,
            equity=10000.0,
            free_margin=9500.0,
            margin_level=900.0,
            currency="USD",
            leverage=200,
        ),
        position=PositionSnapshot(
            net_position=0.0,
            avg_price=0.0,
            floating_pnl=0.0,
            open_positions_count=0,
            pending_orders_count=0,
            side="flat",
        ),
        risk_state=RiskState(
            max_risk_per_trade_pct=1.0,
            max_symbol_exposure_lots=0.50,
            daily_drawdown_pct=0.0,
            consecutive_losses=0,
            cooldown_until_utc=None,
            trading_halted=halted,
            blackout_reason=None,
        ),
        features=FeatureBundle(
            context_tf={
                "adx_strength": adx_h1,
                "di_balance": di_balance,
                "atr_pct": 0.0040,
                "swing_high_h1": swing_high_h1,
                "swing_low_h1": swing_low_h1,
                "atr_abs_h1": atr_m15 * 1.6,
            },
            decision_tf={
                "rsi_centered": rsi_m1,
                "bb_pos": bb_pos_m1,
                "m1_atr_pct": m1_atr_pct,
                "last3_dir": last3_dir,
            },
            execution_tf={
                "spread_to_atr_ratio": 0.05,
                "atr_abs": atr_m15,
                "atr_abs_m15": atr_m15,
                "atr_abs_m5": atr_m5,
                "atr_abs_m1": atr_m1,
                "volume_step": 0.01,
                "volume_min": 0.01,
                "volume_max": 50.0,
            },
            confirm_tf={
                "rsi_centered": rsi_m5,
                "bb_pos": bb_pos_m5,
                "ema20_m5": ema20_m5,
                "ema50_m5": ema50_m5,
                "ema50_m15": ema50_m15,
                "adx_strength_m15": adx_m15,
                "bb_width_pct": bb_width_pct,
                "breakout_high_m15": breakout_high_m15,
                "breakout_low_m15": breakout_low_m15,
            },
        ),
        openclaw_context=OpenClawContext(mode="normal"),
        active_baskets=active_baskets or [],
        dxy_features={"slope_z": dxy_slope_z},
        vix_features={"z_score": vix_z},
    )
