from __future__ import annotations

from app.models import (
    AccountSnapshot,
    FeatureBundle,
    MarketSnapshot,
    OpenClawContext,
    PositionSnapshot,
    RiskState,
    V5BurstRequest,
)


def make_v5_request(
    *,
    halted: bool = False,
    spread_points: float = 10.0,
    last_close: float = 4170.00,
    rsi_centered: float = 0.10,
    bb_pos: float = 0.20,
    tick_momentum_signed: float = 1.0,
    tick_volume_z: float = 1.0,
    atr_m1_percentile: float = 0.55,
    atr_m1_ratio: float = 1.0,
    vsa_volume_z: float = 0.0,
    vsa_range_z: float = 0.0,
    dom_imbalance: float = 0.0,
    di_balance: float = 0.15,
    active_basket_bursts: int = 0,
    active_basket_side: str = "",
    last_burst_ms_ago: int = 999999,
    margin_level_pct: float = 900.0,
    request_id: str = "TEST-V5-2026-05-21T09:00:00Z",
) -> V5BurstRequest:
    return V5BurstRequest(
        schema_version="v5-burst-request.v1",
        request_id=request_id,
        mode="paper",
        timestamp_utc="2026-05-21T09:00:00+00:00",
        symbol="XAUUSD",
        timeframe="TICK",
        bar_index=0,
        market=MarketSnapshot(
            bid=last_close - 0.05,
            ask=last_close + 0.05,
            last_close=last_close,
            spread_points=spread_points,
            digits=2,
            stops_level_points=0,
            freeze_level_points=0,
            tick_size=0.01,
            tick_value=1.0,
        ),
        account=AccountSnapshot(
            login="demo-1",
            balance=10000.0,
            equity=10000.0,
            free_margin=9500.0,
            margin_level=margin_level_pct,
            currency="USD",
            leverage=200,
        ),
        position=PositionSnapshot(
            net_position=0.0, avg_price=0.0, floating_pnl=0.0,
            open_positions_count=0, pending_orders_count=0, side="flat",
        ),
        risk_state=RiskState(
            max_risk_per_trade_pct=0.5,
            max_symbol_exposure_lots=0.30,
            daily_drawdown_pct=0.0,
            consecutive_losses=0,
            cooldown_until_utc=None,
            trading_halted=halted,
            blackout_reason=None,
        ),
        features=FeatureBundle(
            context_tf={"adx_strength": 0.25, "di_balance": di_balance, "atr_pct": 0.0},
            decision_tf={
                "rsi_centered": rsi_centered,
                "bb_pos": bb_pos,
                "tick_momentum_signed": tick_momentum_signed,
                "tick_volume_z": tick_volume_z,
                "atr_m1_percentile": atr_m1_percentile,
                "atr_m1_ratio": atr_m1_ratio,
                "vsa_volume_z": vsa_volume_z,
                "vsa_range_z": vsa_range_z,
                "dom_imbalance": dom_imbalance,
            },
            execution_tf={
                "spread_to_atr_ratio": 0.0, "atr_abs": 0.0,
                "volume_step": 0.01, "volume_min": 0.01, "volume_max": 50.0,
            },
        ),
        openclaw_context=OpenClawContext(mode="normal"),
        active_basket_bursts=active_basket_bursts,
        active_basket_side=active_basket_side,
        last_burst_ms_ago=last_burst_ms_ago,
        margin_level_pct=margin_level_pct,
    )
